### ISSUE TITLE
Cannot render XYZ tiles in VR

### ISSUE THREAD

**Issue by h0ldemslav** [NASA-AMMOS/3DTilesRendererJS#1301]
### Question

Hi,

I've been trying to render XYZ tiles (ellipsoid) in VR and can't really make it work. It's partially related to #1256, where I wrote that I couldn't render tiles on demand in VR mode. 

However, I was able to solve that on demand problem by reentering the VR mode, which doesn't seem to work with XYZ tiles, even though they're rendered straight away. They just disappear once in VR and the previously described workaround doesn't fix the problem. 

I can see XYZ tiles rendered in Meta Quest Pro (and even manipulate with them using vr controllers) in Meta's browser but once I enter VR mode in the browser, they disappear. I can only see axes helper, which I added for debugging purposes. I attached links to the code and live example.

I assume the problem is either with camera or globe controls but I don't really know how to adjust them. Unfortunately, I have very little knowledge but would be very grateful if somebody can point me out to some resources. I appreciate any help. Thanks a lot!

### Supplemental Data

Code: https://github.com/h0ldemslav/xyz-tiles-in-vr-example/blob/main/vr.js
Live example: https://h0ldemslav.github.io/xyz-tiles-in-vr-example/

To simulate VR mode, use Google Chrome and Meta's extension: https://chromewebstore.google.com/detail/immersive-web-emulator/cgffilbpcibhmcfbgggfhfolhkfbhmik
You can find the extension in devtools.

<img width="1470" height="878" alt="Image" src="https://github.com/user-attachments/assets/028686ab-56c2-44ad-94aa-e450515987db" />

<img width="1470" height="875" alt="Image" src="https://github.com/user-attachments/assets/056a4dca-72a5-40fe-92a4-d11e706a0ca7" />

### Library Version

0.4.13

### Three.js Version

r173

**Comment by gkjohnson** [comment]
> Code: https://github.com/h0ldemslav/xyz-tiles-in-vr-example/blob/main/vr.js

Can you provide some instructions for how to run this locally? Running preview does not seem to allow the page to load and running `npx vite dev` and loading the vr page does not seem to work with the emulator.

**Comment by h0ldemslav** [comment]
Hmm, I think I messed up something. I'm so sorry for that. I updated the code. Do this:
1. Clone the repo from this page: https://github.com/h0ldemslav/xyz-tiles-in-vr-example/tree/main
2. Go to the repo folder and run `npm install`
3. Then run `npm run dev`

**Comment by gkjohnson** [comment]
It's still not working for me - I see the following error when enabling VR mode after running `npm run dev` with the emulator:

<img width="789" height="95" alt="Image" src="https://github.com/user-attachments/assets/97f27539-fc22-4feb-a047-7ef0aebbec17" />

**Comment by h0ldemslav** [comment]
There might be a problem with three.js, lol: https://github.com/mrdoob/three.js/issues/31432. Try to lower three.js version to r172, or even lower

**Comment by gkjohnson** [comment]
Worked that time - thanks for the repro. It's been awhile since that demo has been written so it's probably due for some cleanup (the [getCamera](https://threejs.org/docs/?q=xr#api/en/renderers/webxr/WebXRManager.getCamera) no longer takes an argument now, for example). The scale of the globe makes this more difficult compared to more local scopes like the Mars data set - a globe VR demo would be great to have, though. Generally understanding how VR cameras work isn't super straight forward so I'll try to explain what's happening here and we can go from there - apologies if you're already familiar with all this:

VR headsets track themselves relative to a local coordinate frame defined by the room they are operated in. In order to reflect the users movements into the 3d scene the virtual three.js camera is "snapped" to the headsets location relative to that local coordinate system, which means that the area of movement is usually one the scale of a few meters in each dimension or smaller relative to the origin. What that means is that even if you've placed your three.js camera at the earth's radius out the camera is "snapped" to near the world origin (inside the globe) once transitioning to VR and nothing can be rendered.

Since you don't have direct control over the headset position as it moves, you can instead place the camera inside of a THREE.Group (called "workspace" in this case) that that VR camera can be placed relative to. Then in order to move the camera position to where you want you can shift the position of that local coordinate frame. You can see in the VR demo [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/8f5cfb95d5f364e2dac34a7f11a40e84c0e04c0e/example/vr.js#L129-L137) that the "workspace" group rather than the camera is moved when using the controls to shift to a new location.

What this boils down to is that in order to position the VR camera such that it can see the globe that "workspace" object needs to be placed at the globe radius rather than just the camera. Though keep in mind that GlobeControls is not designed to work with VR so navigation will have to be designed and implemented separately. If you want a demo that allows for navigation with and without VR I would keep "2d mouse view" camera and the "VR dummy camera" (the camera parented to a workspace frame) separate and render using the appropriate one.

Hopefully that gives some insight into what's happening. Let me know if that's clear - it would be nice to get a version of this working!

**Comment by h0ldemslav** [comment]
Yeah, this makes sense to me now. I adjusted the position of workspace, so it's at the globe radius (just like you explained), plus stopped updating the controls once in VR and now I can see the globe in VR! The problem now is the navigation using controls, which is probably out of the scope of this issue, and the rotation of the globe in VR. Do you know how to rotate the globe in VR, so it has the same rotation as before entering VR? Otherwise, thanks a lot for your time and answers.

UPD: basically my use case is that I want to go into VR and show tiles on the globe (ideally zoomed) to study them in more detail

**Comment by gkjohnson** [comment]
> The problem now is the navigation using controls, which is probably out of the scope of this issue, and the rotation of the globe in VR

It may be possible to adjust the GlobeControls logic to support VR controllers but realistically I think you'd want a dedicated control scheme for VR. I would start by taking a look at some of the other VR earth-navigation experiences out there already, like Google Earth VR, to see how they handle things. A basic method might just be to use a joystick to rotate the planet (or rather move the camera around the planet).

> Do you know how to rotate the globe in VR, so it has the same rotation as before entering VR?

I would rotate & position the "workspace" rather than rotate the globe. So if the user has navigated the camera to a certain position using mouse controls you can position the workspace at that camera position and it should be at the same location. What your preferred orientation of the workspace is up to you (the user may be facing "towards" the earth or the globe may be below the floor, for example).

You can use the ellipsoid functions if it makes the math more simple for you - note this is just illustrative and untested. You'll have to determine the right orientation from testing:

```js
// camera transform in tiles frame
const matrix = new Matrix4();
matrix.copy( camera.matrixWorld ).premultiply( tiles.group.matrixWorldInverse );

// get lat / lon data of camera orientation
const carto = {};
tiles.ellipsoid.getCartographicFromObjectFrame( matrix, carto, CAMERA_FRAME );

// position the workspace at a fixed height of 10,000m with an ENU (z-up) frame
tiles.ellipsoid.getObjectFrame( carto.lat, carto.lon, 10_000, 0, 0, 0, OBJECT_FRAME );
```

Please share what you wind up making if you can!
